codi_facturier/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from facturier.views import IndexView, CustomerCreateView, CustomerList, CustomerDetail, CustomerUpdateView, CustomerDeleteView

from facturier.views import ProductCreateView, ProductDetailView, ProductUpdateView, ProductDeleteView, ProductListView

from facturier.views import QuotationCreateView, QuotationListView, QuotationDetailView, QuotationAddNewLineView

from facturier.views import UpdateQuotationTypeView, UpdateCommandLineLineView, DeleteCommandLineLineView, QuotationDetailPrintView, QuotationSendEmail


urlpatterns = [
    url(r'^admin/', admin.site.urls,),
    url(r'^login/$', auth_views.LoginView.as_view(),  name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='index'),  name='logout'),

    url(r'^$', IndexView.as_view(), name='index'),

    url(r"^customer/create/$", CustomerCreateView.as_view(), name="customer-create"),
    url(r"^customer/list/$", CustomerList.as_view(), name="customer-list"),
    url(r"^customer/(?P<slug>[-\w]+)/$", CustomerDetail.as_view(), name="customer-detail"),
    url(r"^customer/(?P<slug>[-\w]+)/edit$", CustomerUpdateView.as_view(), name="customer-edit"),
    url(r"^customer/(?P<slug>[-\w]+)/delete$", CustomerDeleteView.as_view(), name="customer-delete"),

    url(r"^product/create/$", ProductCreateView.as_view(), name="product-create"),
    url(r"^product/list/$", ProductListView.as_view(), name="product-list"),
    url(r"^product/(?P<slug>[-\w]+)/$", ProductDetailView.as_view(), name="product-detail"),
    url(r"^product/(?P<slug>[-\w]+)/edit$", ProductUpdateView.as_view(), name="product-edit"),
    url(r"^product/(?P<slug>[-\w]+)/delete$", ProductDeleteView.as_view(), name="product-delete"),

    url(r"^quotation/create/$", QuotationCreateView.as_view(), name="quotation-create"),

    url(r"^(?P<type>[-\w]+)/list/$", QuotationListView.as_view(), name="list"),

    url(r"^(?P<type>[-\w]+)/(?P<pk>[-\w]+)/$", QuotationDetailView.as_view(), name="detail"),


    url(r"^quotation/transform$", UpdateQuotationTypeView.as_view(), name="quotation-type-transform"),
    url(r"^commandline/update$", UpdateCommandLineLineView.as_view(), name="commandline-update"),
    url(r"^commandline/delete$", DeleteCommandLineLineView.as_view(), name="commandline-delete"),

    url(r"^(?P<type>[-\w]+)/(?P<pk>[-\w]+)/pdf$", QuotationDetailPrintView.as_view(), name="quotation-pdf"),
    url(r"^(?P<type>[-\w]+)/(?P<pk>[-\w]+)/sendEmail$", QuotationSendEmail.as_view(), name="quotation-send-pdf"),

    url(r"^quotation/addline$", QuotationAddNewLineView.as_view(), name="quotation-addline"),

] + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facturier/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from autoslug import AutoSlugField
# Create your models here.

class Customer(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    slug = AutoSlugField(populate_from='full_name', unique=True, always_update=True)
    email = models.EmailField()
    country = models.CharField(max_length=30, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    cover = models.ImageField(upload_to="customer",blank=True)

    def full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def __unicode__(self):
        return self.last_name+" "+self.first_name

TYPE_CHOICES = (
    ("QUOTATION", "Quotation"),
    ("BILL", "Bill"),
)
ETAT_CHOICES =(
    ("PAID", "Paid"),
    ("REVIVE", "Revive"),
    ("WAITING", "Waiting"),
)
class Quotation(models.Model):


    quotation_creation_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    bill_creation_date = models.DateTimeField(blank=True, null=True)
    type = models.CharField(max_length=15, choices=TYPE_CHOICES, default="QUOTATION")
    status = models.CharField(max_length=15, choices=ETAT_CHOICES, default="WAITING")

    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)

class Product(models.Model):
    name = models.CharField(max_length=30)
    slug = AutoSlugField(populate_from="name")
    short_description = models.CharField(max_length=200)
    description = models.TextField()
    cover = models.ImageField(upload_to="product",blank=True)
    price = models.FloatField()
    stock = models.IntegerField()

    def __unicode__(self):
        return self.name

class CommandLine(models.Model):
    quantity = models.IntegerField(default=0)

    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quotation = models.ForeignKey(Quotation, on_delete=models.CASCADE)

facturier/forms.py
from django.forms import ModelForm
from .models import Quotation
from django.db import models
from django import forms

class QuotationForm(forms.ModelForm):
    class Meta:
        model = Quotation
        fields = ('type',)

facturier/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import template
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from django.db.models import Q
from django.db.models.signals import post_save
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import View, ListView, TemplateView, CreateView
from django.views.generic import DetailView, UpdateView, DeleteView
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.edit import FormMixin
from django.template.loader import render_to_string, get_template
from django.contrib.auth.mixins import PermissionRequiredMixin

from .forms import QuotationForm
from .models import Customer, Product, Quotation, CommandLine
from .models import ETAT_CHOICES


from django_weasyprint import WeasyTemplateResponseMixin
from extra_views import CreateWithInlinesView, InlineFormSet
from extra_views.generic import GenericInlineFormSet

register = template.Library()

# Create your views here.
class IndexView(TemplateView):
    template_name = "facturier/index.html"

class CustomerCreateView(PermissionRequiredMixin,CreateView):
    permission_required = 'facturier.add_customer'
    model = Customer
    fields = "__all__"
    success_url = '/'

    def get_success_url(self):
        return reverse('customer-detail', args=[self.object.slug] )

class CustomerList(ListView):
    model = Customer
    template_name='facturier/customer_list.html'

    def get_queryset(self):
        query = self.request.GET.get('q',None)

        if query != None:
            return Customer.objects.filter(Q(last_name__icontains=query)|Q(first_name__icontains=query))
        else:
            return Customer.objects.all()

class CustomerDetail(DetailView):
    model = Customer

class CustomerUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'facturier.change_customer'
    model = Customer
    fields = "__all__"
    template_name = 'facturier/customer_edit.html'

    def get_success_url(self):
        return reverse('customer-detail', args=[self.object.slug] )

class CustomerDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'facturier.delete_customer'
    model = Customer
    success_url = '/'
    # template_name = ".html"

class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'facturier.add_product'
    model = Product
    fields = "__all__"
    success_url = '/'

class ProductDetailView(DetailView):
    model = Product

class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'facturier.change_product'
    model = Product
    fields = "__all__"
    template_name = 'facturier/product_edit.html'

    def get_success_url(self):
        return reverse('product-detail', args=[self.object.slug] )

class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'facturier.delete_product'
    model = Product
    success_url = '/'

class ProductListView(ListView):
    model = Product
    template_name='facturier/product_list.html'

    def get_queryset(self):
        query = self.request.GET.get('q',None)

        if query != None:
            return Product.objects.filter(name__icontains=query)
            #filter
        else:
            return Product.objects.all()

class CommandLineInline(InlineFormSet):
    model = CommandLine
    fields = "__all__"

class QuotationCreateView(PermissionRequiredMixin, CreateWithInlinesView):
    permission_required = 'facturier.add_quotation'
    model = Quotation
    inlines = [CommandLineInline,]
    fields = ("customer","type","status",)
    template_name = 'facturier/quotation_form.html'
    success_url = '/'

class QuotationListView(ListView):
    model = Quotation
    def get_context_data(self, **kwargs):
        context = ListView.get_context_data(self, **kwargs)
        context['status'] = ETAT_CHOICES
        return context


    def get_queryset(self):
        query = self.request.GET.get('q',None)
        query2 = self.request.GET.get('filter',None)
        query3 = self.kwargs['type'].upper()
        if query != None:
            if query2 != "":
                return Quotation.objects.filter(Q(customer__last_name__icontains=query)|Q(customer__first_name__icontains=query), Q(status__icontains=query2), Q(type=query3))
            else:
                return Quotation.objects.filter(Q(customer__last_name__icontains=query)|Q(customer__first_name__icontains=query), Q(type=query3))
            #filter
        else:
            return Quotation.objects.filter(type=query3)

@method_decorator(csrf_exempt, name='dispatch')
class QuotationDetailView(DetailView):
    model = Quotation
    form_class = QuotationForm

    def get_queryset(self):
        query = self.kwargs['type'].upper()
        return Quotation.objects.filter(type=query)

    def get_context_data(self, **kwargs):
        context = DetailView.get_context_data(self, **kwargs)
        context['products'] = Product.objects.all().order_by('name')
        context['pdf'] = False
        context['form'] = QuotationForm
        allLine = CommandLine.objects.filter(quotation=self.object.id)
        total = 0
        for line in allLine:
            total += line.product.price*line.quantity
        context['total'] = total
        return context

@method_decorator(csrf_exempt, name='dispatch')
class UpdateQuotationTypeView(PermissionRequiredMixin, View):
    permission_required = 'facturier.change_quotation'
    def post(self, request):
        quotation = Quotation.objects.get(id = request.POST.get("pk"))
        setattr(quotation, 'type', 'BILL')
        quotation.save()
        return JsonResponse({"redirect_url":reverse( "detail", args=["bill", quotation.id])})

@method_decorator(csrf_exempt, name='dispatch')
class UpdateCommandLineLineView(PermissionRequiredMixin, View):
    permission_required = 'facturier.change_quotation'
    def post(self, request):
        commandline = CommandLine.objects.get(id = request.POST.get("pk"))
        setattr(commandline,request.POST.get("name"), request.POST.get("value"))
        commandline.save()
        return HttpResponse({'success' : True})


@method_decorator(csrf_exempt, name='dispatch')
class DeleteCommandLineLineView(PermissionRequiredMixin, View):
    permission_required = 'facturier.delete_commandline'
    def post(self, request):
        commandline = CommandLine.objects.get(pk = request.POST.get("pk"))
        commandline.delete()
        return HttpResponse({'success' : True})

class QuotationDetailPrintView(WeasyTemplateResponseMixin, QuotationDetailView):

    def get_context_data(self, **kwargs):
        context = QuotationDetailView.get_context_data(self, **kwargs)
        context['pdf'] = True
        return context

    pdf_stylesheets = [
        "facturier/static/css/style.css",
    ]

@method_decorator(csrf_exempt, name='dispatch')
class QuotationAddNewLineView(PermissionRequiredMixin, View):
    permission_required = 'facturier.change_quotation'
    def post(self, request):
        quotation = Quotation.objects.get(id=request.POST.get("quotation-pk"))
        product = Product.objects.get(id=request.POST.get("id-product"))
        quantity = int(request.POST.get('quantity'))

        command_line, created = CommandLine.objects.get_or_create(product = product, quotation=quotation)
        if created == True:
            command_line.quantity = quantity
            command_line.save()
            return JsonResponse({"product_id":command_line.product.id,
                                "product_name":command_line.product.name,
                                "quantity":command_line.quantity,
                                "unit_price":command_line.product.price,
                                "command_line_id":command_line.id           
                                })
        else:
            command_line.quantity += quantity
            command_line.save()
            return JsonResponse({'command_line_id' : command_line.id,
                                'quantity':command_line.quantity,
                                })

import weasyprint
                                

class QuotationSendEmail(PermissionRequiredMixin, View):
    """docstring for QuotationSendEmail."""
    permission_required = 'facturier.change_quotation'

    def get(self, request, pk, type):
        quotation = Quotation.objects.get(id=pk)
        customer = quotation.customer
        # print customer.email


        #generate pdf
        html = render_to_string('facturier/quotation_detail.html', {'quotation': quotation})
        url = reverse('detail', args=[type,pk])
        pdf = weasyprint.HTML(string=html, base_url='url').write_pdf(stylesheets=["facturier/static/css/style.css",])
    
        # send email
        to_email = (customer.email,)
        subject = "Your %s " % quotation.type
        email = EmailMessage(subject, body="vla ton devis", from_email="admin@plop.fr", to=to_email)
        email.attach(quotation.type + "_{}".format(customer.last_name) + '.pdf', pdf, "application/pdf")
        email.content_subtype = "pdf"  # Main content is now text/html
        email.send()
        return HttpResponse({'success' : True})

facturier/templates/facturier/aside.html
<form class="form-inline my-2 my-lg-0 searchForm">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
    <select  name="filter">
        <option value="" selected>Status Choices</option>
        {% for status in status %}
        <option value="{{status.1}}">{{status.0}}</option>
        {% endfor %}
    </select>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

</form>

facturier/templates/facturier/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css'%} ">
    <link rel="stylesheet" href="{% static 'css/style.css'%} ">
    <link rel="stylesheet" href="{% static 'css/styleProfile.css'%} ">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'jquery-editable/css/jquery-editable.css'%}">
    <title>Codi_Facturier</title>
</head>

<body>
    {% include "facturier/header.html" %}
    
    {% block content %}
    
    {% endblock content %}
    
    {% include "facturier/footer.html" %}
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'jquery-editable/js/jquery-editable-poshytip.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    {% block extra_script %}
    
    {% endblock extra_script %}
</body>

</html>

facturier/templates/facturier/customer_detail.html
{% extends "facturier/base.html" %}

{% block content %}

<div class="container-profile-detail">
    <div class="row">
        <div class="col-md-6 img">
            {% if customer.cover.url != none %}
            <img class="profile-img img-fluid" src="{{customer.cover.url}}" alt="" class="img-rounded">
            {% else %}
            <img class="profile-img img-fluid" alt="No Cover" class="img-rounded">
            {% endif %}
        </div>
        <div class="col-md-6 details">
            <blockquote>
                <span>
                    <h5>{{customer.last_name}} {{customer.first_name}}</h5>
                    <div class="buttonChanges">
                        <a href="{% url 'customer-edit' customer.slug %}"><i class="fas fa-edit"></i></a>

                        <form id="DeleteForm" action="{% url 'customer-delete' customer.slug %}" method="POST"> 
                            {%csrf_token %}
                            <button id="DeleteSubmit" type="button"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    </div>
                </span>
                <small><cite title="Source Title">{{customer.city}}, {{customer.country}} <i class="icon-map-marker"></i></cite></small>
            </blockquote>
            <p>
                {{customer.email}} <br>
            </p>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_script %}
    <script>
        $(document).ready(function () {
            $("#DeleteSubmit").click(function (event) {
                if (confirm("Click OK to continue?")) {
                    $('#DeleteForm').submit();
                }
            });
        });
    </script>
{% endblock extra_script %}

facturier/templates/facturier/customer_edit.html
{% extends "facturier/base.html" %}

{% block content %}

<form class="formCustomer bg-dark" action="" method="post" enctype="multipart/form-data">{% csrf_token %}

    {{form.as_p}}

    <button class="btn btn-outline-light" type="submit">Edit</button>
</form>

{% endblock content %}

facturier/templates/facturier/customer_form.html
{% extends "facturier/base.html" %}

{% block content %}

<form class="bg-dark formCustomer" action="." method="post" enctype="multipart/form-data">{% csrf_token %}

        {{form.as_p}}

    <button class="btn btn-outline-light" type="submit">Submit</button>
</form>

{% endblock content %}

facturier/templates/facturier/customer_list.html
{% extends "facturier/base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">LastName</th>
                    <th scope="col">FirstName</th>
                    <th scope="col">Email</th>
                    <th scope="col">Profile Link</th>
                </tr>
            </thead>
            <tbody>

                {% for customer in object_list %}
                <tr>
                    <th scope="row">{{customer.id}}</th>
                    <td>{{customer.last_name}}</td>
                    <td>{{customer.first_name}}</td>
                    <td>{{customer.email}}</td>
                    <td><a href="{% url 'customer-detail' customer.slug %}">Profile</a></td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

facturier/templates/facturier/index.html
{% extends "facturier/base.html" %}
    
{% block content %}
<h1>Index</h1>



{% endblock content %}

facturier/templates/facturier/product_edit.html
{% extends "facturier/base.html" %}

{% block content %}

<form class="formCustomer bg-dark" action="" method="post" enctype="multipart/form-data">{% csrf_token %}

    {{form.as_p}}

    <button class="btn btn-outline-light" type="submit">Edit</button>
</form>

{% endblock content %}

facturier/templates/facturier/product_form.html
{% extends "facturier/base.html" %}

{% block content %}

<form class="bg-dark formCustomer" action="." method="post" enctype="multipart/form-data">{% csrf_token %}
        {{form.as_p}}

    <button class="btn btn-outline-light" type="submit">Submit</button>
</form>

{% endblock content %}

facturier/templates/facturier/quotation_detail.html
{% extends "facturier/base.html" %}
{% load static %}

{% load multiply %}

{% block content %}

<div class="container quotation">
    <div class="row">
        <img src="{% static 'img/lapin.png' %}" alt="lapin">
        <h1>Codi-Facturier</h1>
        
    </div>
    
    <div class="row customer-info">
        <div>
            <h5>{{quotation.customer.last_name}}</h5>
            <h5>{{quotation.customer.first_name}}</h5>
            <h5>{{quotation.customer.email}}</h5>
            <h5>{{quotation.customer.city}}</h5>
            <h5>{{quotation.customer.country}}</h5>
            
        </div>
    </div>
    <div class="content">
        <div class="title">
            <h2>{{quotation.get_type_display}} n°{{quotation.id}}</h2>
            {% if quotation.type == "QUOTATION" %}
                {% if perms.quotation and perms.quotation.change_quotation and not pdf%}
                    <button class="btn btn-warning billTransform" value="{{quotation.id}}"> Transform in Bill</button>
                {% endif %}
                <h5>{{quotation.quotation_creation_date}}</h5>
            {% else %}
                <h5>{{quotation.bill_creation_date}}</h5>
            {% endif %}
        </div>

        <div class="row">
            <table class="table quotationLine">
                <thead>
                    <tr>
                        <th scope="col">ID Product</th>
                        <th scope="col">Name</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Unit Price</th>
                        <th scope="col">Subtotal Price</th>
                        {% if quotation.type == "QUOTATION" %}
                        <th scope="col"></th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody class="CommandLineTable">

                    {% for line in quotation.commandline_set.all %}
                        <tr>
                            <th scope="row">{{line.product.id}}</th>
                            <td>{{line.product.name}}</td>
                            
                            
                            {% if quotation.get_type_display == "Quotation" %}
                            <td><a href="#" data-name="quantity" data-type="text" data-pk="{{line.id}}" data-url="{% url 'commandline-update' %}" data-title="enter quantity">{{line.quantity}}
                            </a></td>
                            {% else %}  
                            <td>{{line.quantity}}</td>
                            {% endif %}
                            <td class="unitPrice">{{line.product.price}} $</td>
                            <td class="subtotal">{% multiply line.product.price line.quantity %} $</td>
                            {% if perms.quotation and perms.quotation.change_quotation and not pdf%}
                            {% if quotation.type == "QUOTATION" %}
                            <td><button id="{{line.id}}" class="btn btn-outline-secondary delete">Delete Line</button></td>
                            {% endif %}
                            {% endif %}
                        </tr>
                    {% endfor %}

                    {% if perms.quotation and perms.quotation.change_quotation and not pdf%}
                    {% if quotation.type == "QUOTATION" %}
                    <tr class="add_Line">
                        <th scope="row"></th>
                        <td> 
                            <select class="selectAddProduct" name="">
                            <option selected="selected">Choose Product</option>
                            {% for product in products %}
                            <option value="{{product.id}}">{{product.name}}</option>
                            {% endfor %}
                            </select> 
                        </td>
                        <td> <input id="addQuantityNewLine" type="number" name="quantity" value=""> </td>
                        <td></td>
                        <td></td>
                        <td><button id="addLine" class="btn btn-outline-secondary add">Add Line</button></td>
                    </tr>
                    {% endif %}
                    {% endif %}
                </tbody>
            </table>
            <h4 class="total-h">Total : <span class="total">{{total}}</span>$</h4>
            {% for product in products %}

            <input class="product-list" type="text" value="{{product.name}}" hidden>
            {% endfor %}
            {% if not pdf%}
            <a class="btn btn-warning"  href="{% url "quotation-pdf" quotation.type quotation.id %}">Export PDF</a>
            {% endif %}
            {% if perms.quotation and perms.quotation.change_quotation and not pdf%}
            <a class="btn btn-warning" href="{% url "quotation-send-pdf" quotation.type quotation.id %}">Send Email</a>
            {% endif %}

        </div>
    </div>
</div>


{% endblock content %}

{% block extra_script %}
<script>
$(document).ready(function () {

    $(".billTransform").click(function(){
         $.ajax({
            
            url: "{% url 'quotation-type-transform'%}",
            type : 'POST',
            data : 'pk='+ this.value,
            success : function(response){
                window.location=response.redirect_url;
            },
            error : function(resultat, statut, erreur){
                alert("Request AJAX failed");
            }
        });       
    });

function MathTotal() {
    $cpt = "";
    $total = 0;
    $subtotal = $(".subtotal");
    for (i = 0; i < $subtotal.length; i++) {
        $total += parseFloat($subtotal[i].innerHTML);
    };
    $total = $total.toString();
    $(".total").text($total);
}

function QuantityLineChange() {
$('.editable-click').click(function () {
    console.log("efnefub");
    $('button.editable-submit').click(function () {
        $parentQuantity = $(this).closest(".control-group");
        $quantity = $parentQuantity.find("input").val();

        $parentUnitPrice = $(this).closest("tr");
        $unitPrice = $parentUnitPrice.find(".unitPrice").html();
        $unitPrice = $unitPrice.replace(",", ".");

        $subtot = parseFloat($unitPrice) * $quantity
        $parentSubtotal = $(this).closest("tr");

        $subtotalTd = $parentSubtotal.find(".subtotal");
        $subtotalTd.text($subtot + " $");
    });
});
} 

function DeleteLine(){
    $(".delete").click(function(){
        $tr = $(this).closest("tr");
            $.ajax({
                url: "{% url 'commandline-delete' %}",
                type : 'POST' ,
                data : 'pk=' + this.id,
                success : function(statue){
                console.log("success");
                $tr.remove();
                MathTotal();
                },
                error : function(resultat, statut, erreur){
                alert("Requete AJAX failed");
                },
            });
    MathTotal();
    });
}

$.fn.editable.defaults.mode = "inline";


$('a[data-name=quantity]').editable();

QuantityLineChange();
MathTotal();
DeleteLine();


$("#addLine").click(function(){
    $addProduct = $(".selectAddProduct").val();
    $addQuantity = $("#addQuantityNewLine").val();
    $idQuotation = {{quotation.id}};
    $.ajax({
        url: "{% url 'quotation-addline'%}",
        type : 'POST',
        data : 'quotation-pk=' + $idQuotation + '&id-product=' + $addProduct + '&quantity=' + $addQuantity,
        success : function(request){
            console.log("success");
            console.log(request);
            if (request.product_id != null) {
                $(`<tr>
                    <th scope="row">${request.product_id}</th>
                    <td>${request.product_name}</td>
                <td><a class="editable editable-click" href="#" data-name="quantity" data-type="text" data-pk="${request.command_line_id}"
                    data-url="{% url 'commandline-update' %}"
                    data-title="enter quantity">${request.quantity}
                </a></td>
                <td class="unitPrice">${request.unit_price} $</td>
                <td class="subtotal">${request.unit_price* request.quantity} $</td>
                <td><button id="${request.command_line_id}" class="btn btn-outline-secondary delete">Delete Line</button></td>
            </tr>`).insertBefore(".add_Line");
            $('a[data-name=quantity]').editable();
            } else {
                $input = $('a[data-pk='+request.command_line_id+']')
                $input.text(
                    function(){
                    return request.quantity;
                    });
                $tr = $input.parents("tr");
                $unitPrice = $tr.find(".unitPrice").html();
                $unitPrice = $unitPrice.replace(",", ".");
                $subtot = parseFloat($unitPrice) * request.quantity;
                $subtotalTd = $tr.find(".subtotal");
                $subtotalTd.text($subtot + " $");             
            }
        DeleteLine();
        MathTotal();
        },
        error : function(resultat, statut, erreur){
            alert("Request AJAX failed");
        },
    });
});

QuantityLineChange();
MathTotal();


});
</script>

{% endblock extra_script %}

facturier/templates/facturier/quotation_list.html
{% extends "facturier/base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Quotation creation date</th>
                    <th scope="col">type</th>
                    <th scope="col">Status</th>
                    <th scope="col">Quotation Detail Link</th>
                </tr>
            </thead>
            <tbody>

                {% for quotation in object_list %}
                <tr>
                    <th scope="row">{{quotation.id}}</th>
                    <td>{{quotation.customer.last_name}} {{quotation.customer.first_name}}</td>
                    <td>{{quotation.quotation_creation_date}}</td>
                    <td>{{quotation.get_type_display}}</td>
                    <td>{{quotation.get_status_display}}</td>
                    <td><a href="{% url "detail" quotation.get_type_display.lower quotation.id %}">Link</a></td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
    {% include "facturier/aside.html" %}
    
</div>
{% endblock content %}